name: Execução de Testes
on:
    workflow_call: 

jobs:
    unit-test:
        name: Teste de unidade
        runs-on: ubuntu-latest
        steps:
            - name: Obtendo o código do projeto
              uses: actions/checkout@v4
            - name: Setup dotnet
              uses: actions/setup-dotnet@v4
              with:
                dotnet-version: "8.0.300"
            - name: Execução do teste de Unidade
              working-directory: ./src
              run: dotnet test ./Review-Filmes.Test.Unit/Review-Filmes.Test.Unit.csproj

    integration-test:
      name: Teste de integração
      runs-on: ubuntu-latest
      services:
        postgre:
          image: postgres:latest
          ports: 
            - 5432:5432
          env:
            POSTGRES_USER: review
            POSTGRES_PASSWORD: postgrespwd
            POSTGRES_DB: review-filmes
      steps:
        - name: Obtendo o código do projeto
          uses: actions/checkout@v4

        - name: Setup dotnet
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: "8.0.300"

        - name: Execução do teste de Integração
          working-directory: ./src
          run: dotnet test ./Review-Filmes.Test.Integration/Review-Filmes.Test.Integration.csproj
          env:
            ConnectionStrings__DefaultConnection: "Host=localhost;Port=5432;Database=review-filmes;Username=review;Password=postgrespwd"

